title: WebTecnologie
description: Sviluppo web, soluzioni digitali e applicazioni moderne con integrazioni AI per cloud, enterprise e WordPress.
baseurl: "/struttura-aziendale"
url: "https://webtecnologie.github.io"

markdown: kramdown
logo: assets/img/logo.png
nav:
  - name: Home
    url: /
  - name: Servizi
    url: /servizi
  - name: Progetti
    url: /progetti
  - name: Contatti
    url: /contatti

brand:
  name: WebTecnologie
